### ISSUE TITLE
Mock the data collection for tests.

### ISSUE THREAD

**Issue by arrooney** [AlbertaSat/ex2_services#40]
https://github.com/AlbertaSat/ex2_services/blob/66bf091e2a780fb2ae7c31c18dd27b6f1b7cbda7/Services/source/housekeeping/housekeeping_service.c#L167

**Comment by wagnerd97** [comment]
#41 
https://github.com/AlbertaSat/ex2_athena_software/pull/6

These pull requests implement the STUBBED system used in other modules to bypass data collection via I2C. Let me know if these will be sufficient or if there is something else of it you want me to resolve

**Comment by arrooney** [comment]
@wagnerd97 I think you'll have an easier time just overriding these functions at this level, and directly filling these structs rather than mocking each device (particularly for Athena where there are a bunch of little things going on). Not sure if this was already your plan, but I thought I'd mention it. Should be pretty quick.

**Comment by wagnerd97** [comment]
Yeah that sounds like the cleanest option
